import Foundation

/// A contextual question the user can ask, generated by AI.
struct QuestionSuggestion: Identifiable, Sendable {
    let id: UUID
    let text: String
    let generatedAt: Date

    init(text: String) {
        self.id = UUID()
        self.text = text
        self.generatedAt = .now
    }
}
